Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# a) Addition of 2 in all the elements
arr_add = arr + 2
print("After adding 2 to each element:", arr_add)

# b) Multiply 3 with all the elements
arr_multiply = arr * 3
print("After multiplying each element by 3:", arr_multiply)

# c) Divide every element by 2
arr_divide = arr / 2
print("After dividing each element by 2:", arr_divide)

After adding 2 to each element: [3 4 5 6 7]
After multiplying each element by 3: [ 3  6  9 12 15]
After dividing each element by 2: [0.5 1.  1.5 2.  2.5]

Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]

b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent_value_and_indices(arr):
    unique, counts = np.unique(arr, return_counts=True)
    max_count = counts.max()
    most_frequent = unique[counts == max_count]
    indices = [np.where(arr == value)[0] for value in most_frequent]

    return most_frequent, indices

# for x
most_frequent_x, indices_x = most_frequent_value_and_indices(x)
print("Most frequent value(s) in x:", most_frequent_x)
print("Indices of most frequent value(s) in x:", indices_x)

# for y
most_frequent_y, indices_y = most_frequent_value_and_indices(y)
print("Most frequent value(s) in y:", most_frequent_y)
print("Indices of most frequent value(s) in y:", indices_y)

Most frequent value(s) in x: [1]
Indices of most frequent value(s) in x: [array([0, 5, 7, 8, 9])]
Most frequent value(s) in y: [1 3]
Indices of most frequent value(s) in y: [array([0, 1, 2]), array([4, 8, 9])]

Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column
print(arr[0, 1])

# b) Access 3rd row, 1st column
print(arr[2, 0])

20
70

Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np

# Create a 1-D NumPy array with 25 evenly spaced numbers from 10 to 100
tisnoor = np.linspace(10, 100, 25)

# Print the array
print("1-D Array:", tisnoor)

# Print the dimensions of the array
print("Dimensions of the array:", tisnoor.ndim)

# Print the shape of the array
print("Shape of the array:", tisnoor.shape)

# Print the total number of elements in the array
print("Total number of elements:", tisnoor.size)

# Print the data type of each element in the array
print("Data type of the elements:", tisnoor.dtype)

# Print the total number of bytes consumed by the array
print("Total number of bytes consumed by the array:", tisnoor.nbytes)

# Find the transpose of the array using reshape()
transposed_array = tisnoor.reshape((1, -1))
print("Transpose of the array using reshape():\n", transposed_array)

# Check if the transpose can be done with the T attribute
transposed_using_T = tisnoor.T
print("Transpose of the array using T attribute:\n", transposed_using_T)

1-D Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total number of elements: 25
Data type of the elements: float64
Total number of bytes consumed by the array: 200
Transpose of the array using reshape():
 [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose of the array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values â€“ 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [3]:
import numpy as np

ucs420_tisnoor = np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 15, 20, 35]])

mean_value = np.mean(ucs420_tisnoor)
median_value = np.median(ucs420_tisnoor)
max_value = np.max(ucs420_tisnoor)
min_value = np.min(ucs420_tisnoor)
unique_elements = np.unique(ucs420_tisnoor)

# Reshape
reshaped_ucs420_tisnoor = ucs420_tisnoor.reshape(4, 3)

# Resize
resized_ucs420_tisnoor = np.resize(ucs420_tisnoor, (2, 3))

print("Original Array:")
print(ucs420_tisnoor)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
print("\nReshaped Array (4x3):")
print(reshaped_ucs420_tisnoor)
print("\nResized Array (2x3):")
print(resized_ucs420_tisnoor)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
[[10 20 30]
 [40 50 60]]